# -*- mode: python ; coding: utf-8 -*-
# SupermixStudioX.spec — v48 Frontier Edition
# Generated by build_studio_x_installer.ps1
from PyInstaller.utils.hooks import collect_all
import os

ROOT = os.path.dirname(os.path.abspath(SPEC))

# ── Data / assets ─────────────────────────────────────────────────────────────
datas = [
    ('assets',  'assets'),
    # Benchmark graph embedded in the app at runtime
    (os.path.join(ROOT, 'output', 'v48_benchmark_comparison.png'), 'output'),
    (os.path.join(ROOT, 'output', 'v48_benchmark_results.json'),   'output'),
    # Model bundles (staging dirs created by build script)
    (os.path.join(ROOT, 'build', 'studio_models_stage'),       'bundled_models'),
    (os.path.join(ROOT, 'build', 'studio_base_model_stage'),   'bundled_base_model'),
    # v48 model weights & meta (staged separately to keep them together)
    (os.path.join(ROOT, 'build', 'v48_model_stage'),           'bundled_models_v48'),
    # Manifest / summaries
    (os.path.join(ROOT, 'output', 'supermix_studio_bundled_models_manifest.json'), 'output'),
]

binaries = []
hiddenimports = []

for pkg in ('webview', 'pythonnet', 'clr_loader', 'cffi', 'flask', 'werkzeug', 'PIL', 'sympy', 'mpmath',
            'safetensors', 'transformers', 'peft', 'torch'):
    try:
        tmp = collect_all(pkg)
        datas    += tmp[0]
        binaries += tmp[1]
        hiddenimports += tmp[2]
    except Exception:
        pass

a = Analysis(
    [os.path.join('source', 'supermix_multimodel_desktop_app.py')],
    pathex=['source'],
    binaries=binaries,
    datas=datas,
    hiddenimports=hiddenimports + [
        'multimodel_catalog',
        'multimodel_runtime',
        'omni_collective_v42_model',
        'omni_collective_v47_model',
        'omni_collective_v48_model',
        'benchmark_v48',
        '_cffi_backend',
        'unittest',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=['tkinter', 'test'],
    noarchive=False,
    optimize=1,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='SupermixStudioX',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=os.path.join(ROOT, 'assets', 'supermix_qwen_icon.ico'),
    version_file=None,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='SupermixStudioX',
)

